<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_save_and_create_new_gach_chan</name>
   <tag></tag>
   <elementGuidId>9695985d-c1b9-42e5-a7e7-bd57f4050548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLuu_ThemCauHoiGachChan</value>
   </webElementProperties>
</WebElementEntity>
