<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add_answer_multiple_question</name>
   <tag></tag>
   <elementGuidId>f1f4ae44-e8b5-437e-870e-10e8a79b22c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeNhieuLuaChon_btnThemLuaChon</value>
   </webElementProperties>
</WebElementEntity>
