<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add_answer_single_question</name>
   <tag></tag>
   <elementGuidId>6fe81a3a-3237-45c1-b5e7-a7bd9a82264d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframeMotLuaChon_btnThemLuaChon</value>
   </webElementProperties>
</WebElementEntity>
