<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnyQuestion</name>
   <tag></tag>
   <elementGuidId>35711f4e-1b1e-427b-9531-9c7d5b200310</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoaiCauHoi</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AnyNoneCâu hỏi tự luậnCâu hỏi điền khuyếtCâu hỏi điền khuyết loại 2Câu hỏi ghép đôiTrắc nghiệm nhiều lựa chọnTrắc nghiệm một lựa chọnCâu hỏi lựa chọn đúng saiCâu hỏi mệnh đề đúng saiCâu hỏi gạch chân</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-table&quot;)/table[@class=&quot;table table-bordered table-loc&quot;]/tbody[1]/tr[1]/td[3]/div[@class=&quot;loaiCauHoi-any&quot;]/select[@class=&quot;form-control&quot;]</value>
   </webElementProperties>
</WebElementEntity>
