<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_save_and_create_new_matching</name>
   <tag></tag>
   <elementGuidId>3e441481-6cd5-48fa-a800-5e7123133666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLuu_ThemMoiCauHoiGhepDoi</value>
   </webElementProperties>
</WebElementEntity>
