<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_save_and_close_matching</name>
   <tag></tag>
   <elementGuidId>ec5a76c5-2924-4387-a1ef-a471e0dba2b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLuuVaDong_ThemMoiCauHoiGhepDoi</value>
   </webElementProperties>
</WebElementEntity>
