<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_choose_question</name>
   <tag></tag>
   <elementGuidId>39968f3e-e011-4653-b934-beac08c48a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[@class = 'selectglyphicon cusglyphicon glyphicon glyphicon-unchecked'][count(. | //i[@class = 'selectglyphicon cusglyphicon glyphicon glyphicon-unchecked']) = count(//i[@class = 'selectglyphicon cusglyphicon glyphicon glyphicon-unchecked'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toogleSelect(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectglyphicon cusglyphicon glyphicon glyphicon-unchecked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>63370</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[@class = 'selectglyphicon cusglyphicon glyphicon glyphicon-unchecked']</value>
   </webElementProperties>
</WebElementEntity>
