<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Huy</name>
   <tag></tag>
   <elementGuidId>819b29fd-6efd-40e3-9aa4-af4be5696f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;users&quot;)/div[@id=&quot;Content-Courses&quot;]/div[@class=&quot;button-action-group&quot;]/button[@class=&quot;btn btn-cancel btn-fixed-width xm-btn-full-width&quot;][count(. | //*[(text() = 'Hủy' or . = 'Hủy')]) = count(//*[(text() = 'Hủy' or . = 'Hủy')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-cancel btn-fixed-width xm-btn-full-width</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>redirectTo('/categories/index')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hủy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users&quot;)/div[@id=&quot;Content-Courses&quot;]/div[@class=&quot;button-action-group&quot;]/button[@class=&quot;btn btn-cancel btn-fixed-width xm-btn-full-width&quot;]</value>
   </webElementProperties>
</WebElementEntity>
