<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cancel_assign_user</name>
   <tag></tag>
   <elementGuidId>cbad3b16-9214-4056-a237-49a2e484663a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and (text() = 'Hủy' or . = 'Hủy')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;users&quot;)/div[@id=&quot;Content-Courses&quot;]/div[@class=&quot;button-action-group&quot;]/button[@class=&quot;btn btn-cancel btn-fixed-width xm-btn-full-width&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hủy</value>
   </webElementProperties>
</WebElementEntity>
