<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_save_adn_create_new_truefalseclause</name>
   <tag></tag>
   <elementGuidId>d8b87c04-40ca-4b5e-b85f-ad22a842044d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLuu_ThemCauHoiMenhDeDungSai</value>
   </webElementProperties>
</WebElementEntity>
