<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_save_and_close_truefalseclause</name>
   <tag></tag>
   <elementGuidId>7732e2ec-c7c2-45ae-8964-1ff4ce667eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLuuVaDong_ThemCauHoiMenhDeDungSai</value>
   </webElementProperties>
</WebElementEntity>
