<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ckeditor_name_answer_1</name>
   <tag></tag>
   <elementGuidId>21f4e0e7-e6f9-49ea-baae-f5cb6f5f6204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_txtNoiDungPhuongAn_1</value>
   </webElementProperties>
</WebElementEntity>
