<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_branch</name>
   <tag></tag>
   <elementGuidId>b60b53bd-4c63-4354-85d5-889bce907e77</elementGuidId>
   <imagePath>E:\84927141118.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;courseInfo&quot;]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;courseInfo&quot;]/div[1]/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;courseInfo&quot;]/div[1]/div[1]/img</value>
   </webElementProperties>
</WebElementEntity>
